import { canonicalizeCategory, type Category } from '@/lib/taxonomy'

/** Gradient class per category — shared by category tiles and home episode cards. */
export const CATEGORY_TILE_CLASSES: Partial<Record<Category, string>> = {
  Top: 'category-tile-top',
  Politics: 'category-tile-politics',
  Business: 'category-tile-business',
  'Finance & Macroeconomics': 'category-tile-finance',
  Technology: 'category-tile-tech',
  Science: 'category-tile-science',
  'Health & Medicine': 'category-tile-health',
  Sports: 'category-tile-sports',
  Crime: 'category-tile-crime',
  'Math & Patterns': 'category-tile-science-nature',
  'Science & Evidence': 'category-tile-science-nature',
  'Space & Cosmos': 'category-tile-science',
  'History & Context': 'category-tile-history',
  'Health & the Body': 'category-tile-health-wellbeing',
  'Technology & Systems': 'category-tile-tech-coding',
  'Markets & Money': 'category-tile-money-econ',
  'Careers & Work': 'category-tile-business',
  'Arts & Culture': 'category-tile-arts-culture',
  'Earth & Environment': 'category-tile-science-nature',
  'True Crime': 'category-tile-true-crime',
  'Unexplained & Mystery': 'category-tile-mystery',
  'Pop Culture': 'category-tile-pop-culture',
  'Film & TV': 'category-tile-film-tv',
  Music: 'category-tile-music',
  Gaming: 'category-tile-gaming',
  'Fiction & Literature': 'category-tile-arts-culture',
  'Mystery & Thriller': 'category-tile-true-crime',
  'Sci-Fi & Fantasy': 'category-tile-mystery',
  Nonfiction: 'category-tile-history',
  'Biography & Memoir': 'category-tile-film-tv',
  'History & Society': 'category-tile-history',
  'Self-Help & Growth': 'category-tile-wellness',
  'Business & Leadership': 'category-tile-business',
  'Food & Cooking': 'category-tile-food',
  Travel: 'category-tile-travel',
  'Home & Garden': 'category-tile-home-garden',
  'Health & Fitness': 'category-tile-fitness',
  Relationships: 'category-tile-relationships',
  'Personal Finance': 'category-tile-personal-finance',
  'Parenting & Family': 'category-tile-parenting',
  'Style & Fashion': 'category-tile-style',
  'Mindfulness & Wellness': 'category-tile-wellness',
  Pets: 'category-tile-pets',
  'Hip-Hop': 'category-tile-hip-hop',
  Electronic: 'category-tile-electronic',
  Jazz: 'category-tile-jazz',
  Rock: 'category-tile-rock',
  Classical: 'category-tile-classical',
  Ambient: 'category-tile-ambient',
  'R&B': 'category-tile-rnb',
  Latin: 'category-tile-latin',
}

export function categoryTileClass(category: string): string {
  const canonical = canonicalizeCategory(category) as Category
  return CATEGORY_TILE_CLASSES[canonical] ?? 'category-tile-top'
}
