import type { StoryCard } from '@/types/story'

/** Seed data for discovery UI when database is empty or unavailable */
export const MOCK_STORIES: StoryCard[] = [
  {
    id: 'mock-1',
    title: 'Global Semiconductor Supply Chain Realignment',
    language: 'English',
    category: 'Technology',
    geoScope: 'Worldwide',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&h=400&fit=crop',
    audioUrl: null,
    durationSeconds: 420,
    reliabilityIndex: 8.7,
    isCached: true,
    requiresGeneration: false,
  },
  {
    id: 'mock-2',
    title: 'Central Bank Rate Corridor Analysis Q2',
    language: 'English',
    category: 'Finance & Macroeconomics',
    geoScope: 'Region',
    geoRegion: 'North America',
    thumbnailUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400&h=400&fit=crop',
    audioUrl: null,
    durationSeconds: 380,
    reliabilityIndex: 9.1,
    isCached: true,
    requiresGeneration: false,
  },
  {
    id: 'mock-3',
    title: 'Municipal Water Infrastructure Audit',
    language: 'English',
    category: 'Science',
    geoScope: 'Local',
    geoLocal: 'Austin, TX',
    thumbnailUrl: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=400&h=400&fit=crop',
    audioUrl: null,
    durationSeconds: 510,
    reliabilityIndex: 8.2,
    isCached: false,
    requiresGeneration: true,
  },
  {
    id: 'mock-4',
    title: 'Cross-Border Energy Grid Interconnect',
    language: 'Spanish',
    category: 'Business',
    geoScope: 'Country',
    geoCountry: 'Mexico',
    thumbnailUrl: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=400&h=400&fit=crop',
    audioUrl: null,
    durationSeconds: 445,
    reliabilityIndex: 7.9,
    isCached: true,
    requiresGeneration: false,
  },
  {
    id: 'mock-5',
    title: 'Clinical Trial Phase III Outcomes Registry',
    language: 'English',
    category: 'Health & Medicine',
    geoScope: 'Worldwide',
    thumbnailUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400&h=400&fit=crop',
    audioUrl: null,
    durationSeconds: 395,
    reliabilityIndex: 9.4,
    isCached: true,
    requiresGeneration: false,
  },
  {
    id: 'mock-6',
    title: 'Electoral District Boundary Reclassification',
    language: 'English',
    category: 'Politics',
    geoScope: 'State/Province',
    geoState: 'California',
    thumbnailUrl: 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=400&h=400&fit=crop',
    audioUrl: null,
    durationSeconds: 360,
    reliabilityIndex: 8.0,
    isCached: false,
    requiresGeneration: true,
  },
  {
    id: 'mock-7',
    title: 'Professional League Revenue Cap Mechanics',
    language: 'English',
    category: 'Sports',
    geoScope: 'Country',
    geoCountry: 'United States',
    thumbnailUrl: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=400&h=400&fit=crop',
    audioUrl: null,
    durationSeconds: 330,
    reliabilityIndex: 7.5,
    isCached: true,
    requiresGeneration: false,
  },
  {
    id: 'mock-8',
    title: 'Streaming Platform Content Licensing Matrix',
    language: 'English',
    category: 'Entertainment',
    geoScope: 'Worldwide',
    thumbnailUrl: 'https://images.unsplash.com/photo-1522869635100-9f4d5b86b7c6?w=400&h=400&fit=crop',
    audioUrl: null,
    durationSeconds: 400,
    reliabilityIndex: 8.3,
    isCached: true,
    requiresGeneration: false,
  },
  {
    id: 'mock-9',
    title: 'Digital Asset Custody Regulatory Framework',
    language: 'German',
    category: 'Finance & Macroeconomics',
    geoScope: 'Country',
    geoCountry: 'Germany',
    thumbnailUrl: 'https://images.unsplash.com/photo-1639762681485-074b7f938aa0?w=400&h=400&fit=crop',
    audioUrl: null,
    durationSeconds: 475,
    reliabilityIndex: 8.8,
    isCached: false,
    requiresGeneration: true,
  },
  {
    id: 'mock-10',
    title: 'Forensic Case Evidence Chain Protocol',
    language: 'English',
    category: 'Crime',
    geoScope: 'Region',
    geoRegion: 'European Union',
    thumbnailUrl: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=400&h=400&fit=crop',
    audioUrl: null,
    durationSeconds: 520,
    reliabilityIndex: 9.0,
    isCached: true,
    requiresGeneration: false,
  },
]
